services:
 zookeeper:
   image: confluentinc/cp-zookeeper:7.4.4
   container_name: zookeeper_nifi
   hostname: zookeeper
   ports:
     - "2181:2181"
   networks:
     - confluent
   environment:
     ZOOKEEPER_SERVER_ID: 1
     ZOOKEEPER_CLIENT_PORT: 2181
     ZOOKEEPER_TICK_TIME: 2000
     ZOOKEEPER_INIT_LIMIT: 5
     ZOOKEEPER_SYNC_LIMIT: 2
 kafka-1:
   image: confluentinc/cp-kafka:7.4.4
   container_name: kafka-nf
   hostname: kafka-nf
   depends_on:
     - zookeeper
   ports:
     - "9092:9092"
     - "9093:9093"
   networks:
     - confluent
   environment:
     KAFKA_BROKER_ID: 1
     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
     KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
     KAFKA_DELETE_TOPIC_ENABLE: true
     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
     KAFKA_LISTENERS: PLAINTEXT://kafka-nf:9092,PLAINTEXT_HOST://0.0.0.0:9093
     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-nf:9092,PLAINTEXT_HOST://localhost:9093
     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
     KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
 nifi:
   image: apache/nifi:1.21.0
   container_name: nifi
   user: "root"
   ports:
     - "8080:8080"
   networks:
     - confluent
   environment:
     NIFI_WEB_HTTP_PORT: 8080
   volumes:
     - ./nifi_data:/opt/nifi/nifi-current/data
     - ./keystore:/opt/jks/
volumes:
 nifi_data:
networks:
 confluent: